# Generated by Django 4.2.6 on 2023-11-15 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_order_alter_case_base_value_alter_case_buy_assurance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='base_value',
            field=models.PositiveIntegerField(verbose_name='Base value'),
        ),
        migrations.AlterField(
            model_name='case',
            name='buy_assurance',
            field=models.BooleanField(default=False, verbose_name='Buy insurance'),
        ),
        migrations.AlterField(
            model_name='case',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, verbose_name='Capacity'),
        ),
        migrations.AlterField(
            model_name='case',
            name='cover',
            field=models.ImageField(blank=True, upload_to='cases/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='case',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان انتشار'),
        ),
        migrations.AlterField(
            model_name='case',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='case',
            name='end_time',
            field=models.CharField(max_length=200, verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='case',
            name='guaranteed_gain',
            field=models.BooleanField(default=False, verbose_name='Guaranteed gain'),
        ),
        migrations.AlterField(
            model_name='case',
            name='guaranteed_gain_percent',
            field=models.PositiveIntegerField(verbose_name='Guaranteed gain percent'),
        ),
        migrations.AlterField(
            model_name='case',
            name='maker',
            field=models.CharField(max_length=100, verbose_name='Maker'),
        ),
        migrations.AlterField(
            model_name='case',
            name='region',
            field=models.CharField(max_length=100, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('a', 'فعال'), ('s', 'به زودی ...'), ('e', 'خاتمه یافته')], max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='case',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=1000, verbose_name='نشانی'),
        ),
        migrations.AlterField(
            model_name='order',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان انتشار'),
        ),
        migrations.AlterField(
            model_name='order',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='زمان بازبینی'),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='وضعیت پرداخت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='order',
            name='national_code',
            field=models.CharField(max_length=10, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.CharField(max_length=1000, verbose_name='یادداشت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='تلفن همراه'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='base_value',
            field=models.PositiveIntegerField(verbose_name='Base value'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='cases.case', verbose_name='پروژه'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='meter',
            field=models.PositiveIntegerField(default=1, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='cases.order', verbose_name='سفارش'),
        ),
    ]
