# Generated by Django 4.2.6 on 2023-11-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_alter_case_base_value_alter_case_buy_assurance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='base_value',
            field=models.PositiveIntegerField(verbose_name='Min of investment'),
        ),
        migrations.AlterField(
            model_name='case',
            name='buy_assurance',
            field=models.BooleanField(default=False, verbose_name='Buy assurance'),
        ),
    ]
