# Generated by Django 4.2.6 on 2023-12-25 17:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_alter_case_base_value_alter_case_buy_assurance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='base_value',
            field=models.PositiveIntegerField(verbose_name='حداقل خرید'),
        ),
        migrations.AlterField(
            model_name='case',
            name='buy_assurance',
            field=models.BooleanField(default=False, verbose_name='ضمانت خرید'),
        ),
        migrations.AlterField(
            model_name='case',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, verbose_name='ظرفیت'),
        ),
        migrations.AlterField(
            model_name='case',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='case',
            name='end_time',
            field=models.CharField(max_length=200, verbose_name='تاریخ اتمام پروژه'),
        ),
        migrations.AlterField(
            model_name='case',
            name='guaranteed_gain',
            field=models.BooleanField(default=False, verbose_name='سود تضمینی'),
        ),
        migrations.AlterField(
            model_name='case',
            name='guaranteed_gain_percent',
            field=models.PositiveIntegerField(verbose_name='درصد سود تضمینی'),
        ),
        migrations.AlterField(
            model_name='case',
            name='maker',
            field=models.CharField(max_length=100, verbose_name='سازنده'),
        ),
        migrations.AlterField(
            model_name='case',
            name='region',
            field=models.CharField(max_length=100, verbose_name='منطقه'),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('a', 'فعال'), ('s', 'به زودی'), ('e', 'خاتمه یافته')], max_length=10, verbose_name='وضعیت پروژه'),
        ),
        migrations.AlterField(
            model_name='case',
            name='title',
            field=models.CharField(max_length=300, verbose_name='پروژه'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='base_value',
            field=models.PositiveIntegerField(verbose_name='قیمت پایه'),
        ),
    ]
